---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.6-alpine
inputs:
  - name: pybot
run:
  dir: pybot
  path: sh
  args:
    - -ec
    - |
      pip -q install pytest
      pip -q install -r requirements
      cd bot
      mkdir config
      echo <<EOF >./config/config.test.yaml
      tokens:
        weather_token: "${WEATHER_TOKEN}"
        tg_token: "${TG_TOKEN}"
      database:
        host: data/pybot.test.db
      python -m pytest --log-cli-level 1
